/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sysadd2prototype.ToolMenu;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Letty
 */
public class BackUpPanel extends javax.swing.JPanel {
        Process process;
        File file = null;
        File file2 = new File("C:\\Users\\Letty\\Desktop\\Sysadd_Sample_Docs");
    /**
     * Creates new form BackUpPanel
     */
    public BackUpPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWord = new javax.swing.JButton();
        btnNotepad = new javax.swing.JButton();
        btnNotepad2 = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        btnWordPad = new javax.swing.JButton();
        btnPowerpnt = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        btnWord.setText("MS Word");
        btnWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWordActionPerformed(evt);
            }
        });

        btnNotepad.setText("Notepad");
        btnNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotepadActionPerformed(evt);
            }
        });

        btnNotepad2.setText("Notepad++");
        btnNotepad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotepad2ActionPerformed(evt);
            }
        });

        btnExcel.setText("MS Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        btnWordPad.setText("WordPad");
        btnWordPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWordPadActionPerformed(evt);
            }
        });

        btnPowerpnt.setText("MS Powerpoint");
        btnPowerpnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerpntActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPowerpnt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnWordPad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNotepad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNotepad2))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExcel, btnNotepad, btnNotepad2, btnPowerpnt, btnWord, btnWordPad});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNotepad)
                        .addGap(18, 18, 18)
                        .addComponent(btnNotepad2)
                        .addGap(18, 18, 18)
                        .addComponent(btnWordPad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnWord, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPowerpnt)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcel)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnExcel, btnNotepad, btnNotepad2, btnPowerpnt, btnWord, btnWordPad});

    }// </editor-fold>//GEN-END:initComponents

    private void btnWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWordActionPerformed
      
        try {
            process = Runtime.getRuntime().exec("cmd.exe /C start WINWORD.EXE" );
            file = File.createTempFile("Untitled", ".docx", file2);
        } catch (IOException ex) {
            Logger.getLogger(BackUpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnWordActionPerformed

    private void btnNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotepadActionPerformed
        
        try {
            process = Runtime.getRuntime().exec("cmd.exe /C start notepad.EXE" );
            file = File.createTempFile("Untitled", ".txt", file2);
        } catch (IOException ex) {
            Logger.getLogger(BackUpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNotepadActionPerformed

    private void btnNotepad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotepad2ActionPerformed
       
        try {
            process = Runtime.getRuntime().exec("cmd.exe /C start notepad++.EXE" );
            file = File.createTempFile("Untitled", ".ccp", file2);
        } catch (IOException ex) {
            Logger.getLogger(BackUpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNotepad2ActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
       
        try {
            process = Runtime.getRuntime().exec("cmd.exe /C start EXCEL.EXE" );
            file = File.createTempFile("Untitled", ".xlsx", file2);
        } catch (IOException ex) {
            Logger.getLogger(BackUpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnWordPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWordPadActionPerformed
       
        try {
            process = Runtime.getRuntime().exec("cmd.exe /C start wordpad.EXE" );
            file = File.createTempFile("Untitled", ".rtf", file2);
        } catch (IOException ex) {
            Logger.getLogger(BackUpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnWordPadActionPerformed

    private void btnPowerpntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerpntActionPerformed

        try {
            process = Runtime.getRuntime().exec("cmd.exe /C start POWERPNT.EXE" );
            file = File.createTempFile("Untitled", ".pptx", file2);
        } catch (IOException ex) {
            Logger.getLogger(BackUpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPowerpntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnNotepad;
    private javax.swing.JButton btnNotepad2;
    private javax.swing.JButton btnPowerpnt;
    private javax.swing.JButton btnWord;
    private javax.swing.JButton btnWordPad;
    // End of variables declaration//GEN-END:variables
}
