/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sysadd2prototype.ToolMenu;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Letty
 */
public class BackUpFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form BackUpFrame
     */
    public BackUpFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWord = new javax.swing.JButton();
        btnNotepad = new javax.swing.JButton();
        btnNotepad2 = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        btnWordPad = new javax.swing.JButton();
        btnPowerpnt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setClosable(true);
        setIconifiable(true);
        setTitle("Back Up ");

        btnWord.setText("MS Word");
        btnWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWordActionPerformed(evt);
            }
        });

        btnNotepad.setText("Notepad");
        btnNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotepadActionPerformed(evt);
            }
        });

        btnNotepad2.setText("Notepad++");
        btnNotepad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotepad2ActionPerformed(evt);
            }
        });

        btnExcel.setText("MS Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        btnWordPad.setText("WordPad");
        btnWordPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWordPadActionPerformed(evt);
            }
        });

        btnPowerpnt.setText("MS Powerpoint");
        btnPowerpnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerpntActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnWordPad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNotepad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnWord, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(btnNotepad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPowerpnt, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNotepad, btnNotepad2, btnWord});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnWord, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPowerpnt)
                .addGap(18, 18, 18)
                .addComponent(btnExcel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnNotepad)
                .addGap(18, 18, 18)
                .addComponent(btnNotepad2)
                .addGap(18, 18, 18)
                .addComponent(btnWordPad)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnNotepad, btnNotepad2, btnWord});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        Process process;
        try {
            process = Runtime.getRuntime().exec("cmd.exe /C start EXCEL.EXE" );
        } catch (IOException ex) {
            Logger.getLogger(BackUpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnPowerpntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerpntActionPerformed
         Process process;
        try {
            process = Runtime.getRuntime().exec("cmd.exe /C start POWERPNT.EXE" );
        } catch (IOException ex) {
            Logger.getLogger(BackUpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPowerpntActionPerformed

    private void btnWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWordActionPerformed
            Process process;
        try {
            process = Runtime.getRuntime().exec("cmd.exe /C start WINWORD.EXE" );
        } catch (IOException ex) {
            Logger.getLogger(BackUpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_btnWordActionPerformed

    private void btnNotepad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotepad2ActionPerformed
        Process process;
        try {
            process = Runtime.getRuntime().exec("cmd.exe /C start notepad++.EXE" );
        } catch (IOException ex) {
            Logger.getLogger(BackUpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNotepad2ActionPerformed

    private void btnNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotepadActionPerformed
        Process process;
        try {
            process = Runtime.getRuntime().exec("cmd.exe /C start notepad.EXE" );
        } catch (IOException ex) {
            Logger.getLogger(BackUpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNotepadActionPerformed

    private void btnWordPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWordPadActionPerformed
         Process process;
        try {
            process = Runtime.getRuntime().exec("cmd.exe /C start wordpad.EXE" );
        } catch (IOException ex) {
            Logger.getLogger(BackUpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnWordPadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnNotepad;
    private javax.swing.JButton btnNotepad2;
    private javax.swing.JButton btnPowerpnt;
    private javax.swing.JButton btnWord;
    private javax.swing.JButton btnWordPad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
