/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sysadd2prototype.ToolMenu;

import java.io.File;

/**
 *
 * @author Letty
 */
public class DocumentFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form BackUpFrame
     */
    public DocumentFrame() {
        
        initComponents();
    }

    public DocumentFrame(String string, boolean b, boolean b0, boolean b1, boolean b2) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BUScroll = new javax.swing.JScrollPane();
        BUTreeFile = new javax.swing.JTree();
        BUDisplay = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Documents");

        DocTreeFile.setModel(new DocTreeFile(new File("C:\\Users\\Letty\\Desktop\\Sysadd1\\Status Reports")));
        BUScroll.setViewportView(BUTreeFile);

        javax.swing.GroupLayout BUDisplayLayout = new javax.swing.GroupLayout(BUDisplay);
        BUDisplay.setLayout(BUDisplayLayout);
        BUDisplayLayout.setHorizontalGroup(
            BUDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        BUDisplayLayout.setVerticalGroup(
            BUDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BUScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BUDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BUScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(BUDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BUDisplay;
    private javax.swing.JScrollPane BUScroll;
    private javax.swing.JTree BUTreeFile;
    // End of variables declaration//GEN-END:variables
}
