/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sysadd2prototype;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Letty
 */
public class backUpForm extends javax.swing.JFrame {

    /**
     * Creates new form backUpForm
     */
    public backUpForm() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jWord = new javax.swing.JButton();
        jNotepad = new javax.swing.JButton();
        jExcel = new javax.swing.JButton();
        jPowerpoint = new javax.swing.JButton();
        jNotepad2 = new javax.swing.JButton();
        jExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jWord.setText("Word");
        jWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWordActionPerformed(evt);
            }
        });

        jNotepad.setText("Notepad");
        jNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNotepadActionPerformed(evt);
            }
        });

        jExcel.setText("Excel");
        jExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExcelActionPerformed(evt);
            }
        });

        jPowerpoint.setText("Powerpoint");
        jPowerpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPowerpointActionPerformed(evt);
            }
        });

        jNotepad2.setText("Notepad++");
        jNotepad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNotepad2ActionPerformed(evt);
            }
        });

        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jExit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jWord)
                        .addGap(32, 32, 32)
                        .addComponent(jPowerpoint)
                        .addGap(34, 34, 34)
                        .addComponent(jExcel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jNotepad)
                        .addGap(44, 44, 44)
                        .addComponent(jNotepad2)
                        .addGap(36, 36, 36)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWord)
                    .addComponent(jPowerpoint)
                    .addComponent(jExcel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNotepad2)
                    .addComponent(jNotepad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jExit)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWordActionPerformed
         try {
            Process wordProcess;
            wordProcess = Runtime.getRuntime().exec("cmd.exe /C start WINWORD.EXE" );
        } catch (IOException ex) {
            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jWordActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        this.dispose();
        new mainForm().setVisible(true);
    }//GEN-LAST:event_jExitActionPerformed

    private void jNotepad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNotepad2ActionPerformed
        try {
            Process notepad2Process;
            notepad2Process = Runtime.getRuntime().exec("cmd.exe /C start notepad++.exe" );
        } catch (IOException ex) {
            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_jNotepad2ActionPerformed

    private void jNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNotepadActionPerformed
       try {
            Process notepadProcess;
            notepadProcess = Runtime.getRuntime().exec("cmd.exe /C start notepad.exe" );
        } catch (IOException ex) {
            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jNotepadActionPerformed

    private void jPowerpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPowerpointActionPerformed
     try {
            Process powerpntProcess;
            powerpntProcess = Runtime.getRuntime().exec("cmd.exe /C start POWERPNT.EXE" );
        } catch (IOException ex) {
            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jPowerpointActionPerformed

    private void jExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExcelActionPerformed
        try {
            Process excelProcess;
            excelProcess = Runtime.getRuntime().exec("cmd.exe /C start EXCEL.EXE" );
        } catch (IOException ex) {
            Logger.getLogger(mainForm.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_jExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(backUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(backUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(backUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(backUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new backUpForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jExcel;
    private javax.swing.JButton jExit;
    private javax.swing.JButton jNotepad;
    private javax.swing.JButton jNotepad2;
    private javax.swing.JButton jPowerpoint;
    private javax.swing.JButton jWord;
    // End of variables declaration//GEN-END:variables
}
