/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sysadd2prototype;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Letty
 */
public class loginForm extends javax.swing.JDialog {
    Connection conn = new DBConnection().connect();

    /**
     * Creates new form loginForm
     * @param parent
     * @param modal
     */
    public loginForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
      setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswd = new javax.swing.JLabel();
        jUsernameF = new javax.swing.JTextField();
        jPasswdF = new javax.swing.JPasswordField();
        jLogin = new javax.swing.JButton();
        jCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jIcon = new javax.swing.JLabel();
        jUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPasswd.setText("Password");

        jPasswdF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswdFKeyPressed(evt);
            }
        });

        jLogin.setText("Login");
        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });

        jCancel.setText("Cancel");
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });

        jPanel1.setLayout(null);

        jIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Letty\\Desktop\\logo.png")); // NOI18N
        jPanel1.add(jIcon);
        jIcon.setBounds(10, 0, 220, 210);

        jUsername.setText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLogin)
                        .addGap(18, 18, 18)
                        .addComponent(jCancel)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPasswd)
                            .addComponent(jUsername))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jUsernameF)
                            .addComponent(jPasswdF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jUsername)
                            .addComponent(jUsernameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswd)
                            .addComponent(jPasswdF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLogin)
                            .addComponent(jCancel)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswdFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswdFKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             String sql = "select * from loginform where lf_Uname=? and lf_Passwd=?";
       try {
           PreparedStatement ps = conn.prepareStatement(sql);
           ps.setString(1,jUsernameF.getText());
           ps.setString(2,jPasswdF.getText());
           ResultSet rs = ps.executeQuery();
           if (rs.next()){
                JOptionPane.showMessageDialog(null, "Welcome!!");
               this.dispose();
               mainForm mf = new mainForm();
               mf.show();
           }else
           {
               JOptionPane.showMessageDialog(null,"Invalid Username/Password");
               jUsernameF.setText(null);
                jPasswdF.setText(null);
                this.setVisible(true);
           }
       }catch (SQLException | HeadlessException e){
           
       }
        }
    }//GEN-LAST:event_jPasswdFKeyPressed

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
       String sql = "select * from loginform where lf_Uname=? and lf_Passwd=?";
       try {
           PreparedStatement ps = conn.prepareStatement(sql);
           ps.setString(1,jUsernameF.getText());
           ps.setString(2,jPasswdF.getText());
           ResultSet rs = ps.executeQuery();
           if (rs.next()){
               this.dispose();
               mainForm mf = new mainForm();
               mf.show();
           }else
           {
               JOptionPane.showMessageDialog(null,"Invalid Username/Password");
               jUsernameF.setText(null);
                jPasswdF.setText(null);
                this.setVisible(true);
           }
       }catch (SQLException | HeadlessException e){
           
       }
    }//GEN-LAST:event_jLoginActionPerformed

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            loginForm dialog;
            dialog = new loginForm(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                
                @Override
                public void windowClosing(java.awt.event.WindowEvent e){
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancel;
    private javax.swing.JLabel jIcon;
    private javax.swing.JButton jLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPasswd;
    private javax.swing.JPasswordField jPasswdF;
    private javax.swing.JLabel jUsername;
    private javax.swing.JTextField jUsernameF;
    // End of variables declaration//GEN-END:variables
}
