/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sysadd2prototype;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Letty
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLogout = new javax.swing.JButton();
        jDocu = new javax.swing.JButton();
        jBackUp = new javax.swing.JButton();
        jRetrive = new javax.swing.JButton();
        jLogs = new javax.swing.JButton();
        jMemCheck = new javax.swing.JButton();
        jSourceF = new javax.swing.JTextField();
        jSource = new javax.swing.JButton();
        jDestF = new javax.swing.JTextField();
        jDest = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLogout.setText("Log Out");
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });

        jDocu.setText("Documents");

        jBackUp.setText("Back-Up");
        jBackUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackUpActionPerformed(evt);
            }
        });

        jRetrive.setText("Retrieve");
        jRetrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRetriveActionPerformed(evt);
            }
        });

        jLogs.setText("Logs");

        jMemCheck.setText("Memory Check");

        jSource.setText("Source");
        jSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSourceActionPerformed(evt);
            }
        });

        jDest.setText("Destination");
        jDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(377, Short.MAX_VALUE)
                        .addComponent(jLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDestF, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jSourceF))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSource)
                            .addComponent(jDest))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDocu)
                    .addComponent(jMemCheck))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBackUp)
                    .addComponent(jRetrive)
                    .addComponent(jLogs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBackUp, jDocu, jLogs, jMemCheck, jRetrive});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jDest, jSource});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSourceF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSource))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDestF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBackUp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRetrive, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jMemCheck)
                        .addGap(18, 18, 18)
                        .addComponent(jDocu)
                        .addGap(28, 28, 28)))
                .addGap(34, 34, 34)
                .addComponent(jLogout)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBackUp, jDocu, jLogs, jMemCheck, jRetrive});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jDest, jSource});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed

      this.dispose();
      loginForm lf;
      lf = new loginForm(new javax.swing.JFrame(), true);
      lf.show();
    }//GEN-LAST:event_jLogoutActionPerformed

    private void jBackUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackUpActionPerformed
        this.dispose();
        new backUpForm().setVisible(true);

    }//GEN-LAST:event_jBackUpActionPerformed

    private void jRetriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRetriveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRetriveActionPerformed

    private void jSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSourceActionPerformed
               JFileChooser FChooser = new JFileChooser();
               FChooser.setCurrentDirectory(new java.io.File("."));
               FChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
               FChooser.setAcceptAllFileFilterUsed(false);
               
              int FChooserVal = FChooser.showOpenDialog(this);
              if (JFileChooser.APPROVE_OPTION == FChooserVal){
                File f = FChooser.getCurrentDirectory();
               String fname = f.getAbsolutePath();
               jSourceF.setText(fname);
              } else {
                  System.out.println("Directory access cancelled by user.");
              }
    }//GEN-LAST:event_jSourceActionPerformed

    private void jDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDestActionPerformed
         JFileChooser FChooser = new JFileChooser();
               FChooser.setCurrentDirectory(new java.io.File("."));
               FChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
               FChooser.setAcceptAllFileFilterUsed(false);
               
              int FChooserVal = FChooser.showOpenDialog(this);
              if (JFileChooser.APPROVE_OPTION == FChooserVal){
                File f = FChooser.getCurrentDirectory();
               String fname = f.getAbsolutePath();
               jDestF.setText(fname);
              } else {
                  System.out.println("Diretory access cancelled by user.");
              }
    }//GEN-LAST:event_jDestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mainForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackUp;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JButton jDest;
    private javax.swing.JTextField jDestF;
    private javax.swing.JButton jDocu;
    private javax.swing.JButton jLogout;
    private javax.swing.JButton jLogs;
    private javax.swing.JButton jMemCheck;
    private javax.swing.JButton jRetrive;
    private javax.swing.JButton jSource;
    private javax.swing.JTextField jSourceF;
    // End of variables declaration//GEN-END:variables
}
