/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sysadd2prototype;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sysadd2prototype.ToolMenu.BackUpFrame;
import sysadd2prototype.ToolMenu.DocTreeFile;
import sysadd2prototype.ToolMenu.DocumentFrame;

/**
 *
 * @author Letty
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        FileTree = new javax.swing.JTree();
        btnBackUp = new javax.swing.JButton();
        btnRetrieve = new javax.swing.JButton();
        btnScan = new javax.swing.JButton();
        btnFileScan = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        FDocu = new javax.swing.JMenuItem();
        FExit = new javax.swing.JMenuItem();
        LogMenu = new javax.swing.JMenu();
        LView = new javax.swing.JMenuItem();
        LDownload = new javax.swing.JMenuItem();
        AboutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DocTreeFile.setModel(new DocTreeFile(new File ("C:\\Users\\Letty\\Desktop\\Github\\Project-Protection")));
        jScrollPane1.setViewportView(FileTree);

        btnBackUp.setText("Back Up");

        btnRetrieve.setText("Retrieve");

        btnScan.setText("Memory Scan");

        btnFileScan.setText("File Scan");

        Desktop.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(btnBackUp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(btnRetrieve, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(btnScan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(btnFileScan, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnScan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFileScan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBackUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRetrieve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DesktopLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DesktopLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnScan)
                        .addGap(18, 18, 18)
                        .addComponent(btnFileScan)
                        .addGap(18, 18, 18)
                        .addComponent(btnBackUp)
                        .addGap(18, 18, 18)
                        .addComponent(btnRetrieve)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        DesktopLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBackUp, btnRetrieve});

        FileMenu.setText("File");

        FDocu.setText("Documents");
        FDocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FDocuActionPerformed(evt);
            }
        });
        FileMenu.add(FDocu);

        FExit.setText("Exit");
        FExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FExitActionPerformed(evt);
            }
        });
        FileMenu.add(FExit);

        MenuBar.add(FileMenu);

        LogMenu.setText("Logs");

        LView.setText("View");
        LogMenu.add(LView);

        LDownload.setText("Download");
        LogMenu.add(LDownload);

        MenuBar.add(LogMenu);

        AboutMenu.setText("About");
        MenuBar.add(AboutMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FExitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_FExitActionPerformed

    private void FDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDocuActionPerformed
        DocumentFrame docF = new DocumentFrame();
        Desktop.add(docF);
        docF.setVisible(true);
    }//GEN-LAST:event_FDocuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AboutMenu;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem FDocu;
    private javax.swing.JMenuItem FExit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JTree FileTree;
    private javax.swing.JMenuItem LDownload;
    private javax.swing.JMenuItem LView;
    private javax.swing.JMenu LogMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton btnBackUp;
    private javax.swing.JButton btnFileScan;
    private javax.swing.JButton btnRetrieve;
    private javax.swing.JButton btnScan;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
