/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sysadd2prototype;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileSystemView;
import javax.swing.tree.DefaultTreeModel;
import sysadd2prototype.ToolMenu.BackUpPanel;
import sysadd2prototype.ToolMenu.FileTreePanel;
import sysadd2prototype.ToolMenu.MemoryCheckPanel;
import sysadd2prototype.ToolMenu.ViewLogsPanel;

/**
 *
 * @author Letty
 */
public class MainFrame extends javax.swing.JFrame {
        GridBagLayout layout = new GridBagLayout();
        BackUpPanel BUPanel;
        FileTreePanel FTPanel;
        MemoryCheckPanel MCPanel;
        ViewLogsPanel VLPanel;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        BUPanel = new BackUpPanel();
        FTPanel = new FileTreePanel();
        MCPanel = new MemoryCheckPanel();
        VLPanel = new ViewLogsPanel();
        PanelChange.setLayout(layout);
        GridBagConstraints cons = new GridBagConstraints ();
        cons.gridx=0;
        cons.gridy=0;
        PanelChange.add(BUPanel, cons);
        PanelChange.add(FTPanel,cons);
        PanelChange.add(MCPanel, cons);
        PanelChange.add(VLPanel, cons);
        BUPanel.setVisible(false);
        MCPanel.setVisible(false);
        VLPanel.setVisible(false);
        FTPanel.setVisible(true);
        
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnScan = new javax.swing.JButton();
        btnFileScan = new javax.swing.JButton();
        btnBackUp = new javax.swing.JButton();
        btnRetrieve = new javax.swing.JButton();
        PanelChange = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        FExit = new javax.swing.JMenuItem();
        LogMenu = new javax.swing.JMenu();
        LView = new javax.swing.JMenuItem();
        LDownload = new javax.swing.JMenuItem();
        AboutMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(null);

        btnScan.setText("Memory Scan");
        btnScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanActionPerformed(evt);
            }
        });
        jPanel1.add(btnScan);
        btnScan.setBounds(10, 70, 120, 23);

        btnFileScan.setText("File Scan");
        btnFileScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileScanActionPerformed(evt);
            }
        });
        jPanel1.add(btnFileScan);
        btnFileScan.setBounds(10, 100, 120, 23);

        btnBackUp.setText("Back Up");
        btnBackUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackUp);
        btnBackUp.setBounds(10, 130, 120, 23);

        btnRetrieve.setText("Retrieve");
        btnRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetrieve);
        btnRetrieve.setBounds(10, 160, 120, 23);

        PanelChange.setForeground(new java.awt.Color(60, 63, 65));
        PanelChange.setLayout(new java.awt.BorderLayout());

        FileMenu.setText("File");

        FExit.setText("Exit");
        FExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FExitActionPerformed(evt);
            }
        });
        FileMenu.add(FExit);

        MenuBar.add(FileMenu);

        LogMenu.setText("Logs");

        LView.setText("View");
        LView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LViewActionPerformed(evt);
            }
        });
        LogMenu.add(LView);

        LDownload.setText("Download");
        LogMenu.add(LDownload);

        MenuBar.add(LogMenu);

        AboutMenu.setText("About");
        MenuBar.add(AboutMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelChange, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
            .addComponent(PanelChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FExitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_FExitActionPerformed

    private void btnRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveActionPerformed
        BUPanel.setVisible(false);
        MCPanel.setVisible(false);
        VLPanel.setVisible(false);
        FTPanel.setVisible(true);      
    }//GEN-LAST:event_btnRetrieveActionPerformed

    private void btnBackUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackUpActionPerformed
        BUPanel.setVisible(true);
        FTPanel.setVisible(false);
        VLPanel.setVisible(false);
        MCPanel.setVisible(false);
    }//GEN-LAST:event_btnBackUpActionPerformed

    private void btnFileScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileScanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFileScanActionPerformed

    private void btnScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanActionPerformed
        FileSystemView fsv = FileSystemView.getFileSystemView();
        File file = new File("C:/");
        int gb = 1024*1024*1024;  
        double TotalSpace = (int) (file.getTotalSpace()/gb);
        double UsableSpace = (int) (file.getUsableSpace()/gb);
        double FreeSpace = (int) (file.getFreeSpace()/gb);
        double percent = (int)((FreeSpace/TotalSpace)* 100);
        BUPanel.setVisible(false);
        FTPanel.setVisible(false);
        VLPanel.setVisible(false);
                MCPanel.MemCheckOutput.setText("Drive Letter: " + file + 
                "\nType: " + fsv.getSystemTypeDescription(file) + 
                "\nTotal space: " + TotalSpace + " GB" +
                "\nUsed space: " + UsableSpace + " GB" +
                "\nFree space: " + FreeSpace +  " GB" +
                "\nPercent: " +  percent +  "%");
                MCPanel.setVisible(true);   
                FileWriter MemScanLogs = null;
            try {
                MemScanLogs = new FileWriter ("C:\\Users\\Letty\\Desktop\\SYSADD-Prototype\\Logs\\MemScanLogs.txt");
                  MCPanel.MemCheckOutput.write(MemScanLogs);
                  System.out.println("File Saved");
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_btnScanActionPerformed

    private void LViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LViewActionPerformed
        BUPanel.setVisible(false);
        MCPanel.setVisible(false);
        VLPanel.setVisible(true);
        FTPanel.setVisible(false);
    }//GEN-LAST:event_LViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AboutMenu;
    private javax.swing.JMenuItem FExit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem LDownload;
    private javax.swing.JMenuItem LView;
    private javax.swing.JMenu LogMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel PanelChange;
    private javax.swing.JButton btnBackUp;
    private javax.swing.JButton btnFileScan;
    private javax.swing.JButton btnRetrieve;
    private javax.swing.JButton btnScan;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
